# This file contains values from Cookiecutter

default_context:
  project_name: "redis-bandit"
  project_description: "A Python, redis-backed, distributed Multi-Armed Bandit Framework. The goal is being able to scale a MAB horizontally."
  organization: "deeplearningbrasil"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.7
  github_name: "deeplearningbrasil"
  email: "fernando.camargo.ai@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
